{% set version = "3.1.0" %}

package:
  name: pymol-open-source
  version: {{ version }}

source:
  url: https://github.com/schrodinger/pymol-open-source/archive/v{{ version }}.tar.gz
  sha256: 54306d65060bd58ed8b3dab1a8af521aeb4fd417871f15f463ff05ccb4e121fe

build:
  skip: true  # [py>312]
  number: 2
  script: {{ PYTHON }} setup.py install --use-msgpackc=no

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
  host:
    - python
    - pip
    - numpy >=2.0
    - setuptools >=69.2.0
    - glew
    - libglu                         # [linux]
    - libpng
    - freetype
    - libxml2
    - glm
    - xorg-libxfixes
    - libnetcdf
  run:
    - python
    - {{ pin_compatible("libnetcdf") }}
    - libpng
    - freetype
    - pyqt
    - glm
    - pmw

test:
  requires:
    - requests
  files:
    - test.py
  commands:
    - python test.py

app:
  entry: pymol
  summary: PyMOL molecular visualization system

about:
  home: https://pymol.org/
  license: LicenseRef-PyMOL
  license_file: LICENSE.txt
  summary: A user-sponsored molecular visualization system. PyMOL is a trademark of Schrodinger, LLC.
  description: |
    PyMOL is a molecular visualization software with a Python based command line.
    This is a user-created build based on the open-source variant of the PyMOL software.
    PyMOL is a trademark of Schrodinger, LLC.
  doc_url: https://pymolwiki.org/
  dev_url: https://github.com/schrodinger/pymol-open-source/

extra:
  recipe-maintainers:
    - padix-key
    - awacha
    - bkpoon
